export const menuCategories = [
  {
    id: 'rice-bowls',
    shortName: 'Rice bowls',
    eyebrow: 'Bowls',
    title: 'Vegan Rice Bowls',
    description: 'A hearty rice base layered with savoury salad mix, crisp cucumber, pickled carrots, mukimame, fried shallots, roasted peanuts, peanut hoisin sauce, and warm soup.',
    note: 'Rice and salad bowls contain peanuts and fried shallots containing gluten. Both can be omitted on request.',
    dishes: [
      ['Roasted Pulled Pork & Cracklings Rice Bowl', '$15.90', ['P']],
      ['Lemongrass Beef Rice Bowl', '$15.90', ['P']],
      ['Pepper Mushroom & Chicken Rice Bowl', '$15.90', ['P']],
      ['Tofu & Savoury Salad Rice Bowl', '$15.90', ['P']],
      ['Lemongrass Tofu Rice Bowl', '$15.90', ['P'], true],
    ],
  },
  {
    id: 'salad-bowls',
    shortName: 'Salad bowls',
    eyebrow: 'Bowls',
    title: 'Vegan Salad Bowls',
    description: 'Vermicelli noodles under savoury salad mix with iceberg lettuce, pickled carrots, cucumber, fried shallots, roasted peanuts, and authentic vegan fish sauce.',
    note: 'Rice and salad bowls contain peanuts and fried shallots containing gluten. Both can be omitted on request.',
    dishes: [
      ['Pulled Pork & Cracklings Salad Bowl', '$16.90', ['P']],
      ['Lemongrass Beef Salad Bowl', '$16.90', ['P']],
      ['Pepper Mushroom & Chicken Salad Bowl', '$16.90', ['P']],
      ['Tofu and Spring Rolls Salad Bowl', '$16.90', ['P', 'G'], true],
    ],
  },
  {
    id: 'rice-paper-rolls',
    shortName: 'Rice paper rolls',
    eyebrow: 'Fresh rolls',
    title: 'Vegan Rice Paper Rolls',
    description: 'Fresh, light Vietnamese classics filled with savoury salad mix, pickled carrots, cucumber, and crisp lettuce. Served with house-made peanut hoisin sauce.',
    dishes: [
      ['Pulled Pork & Cracklings RPR', '$4.50 each', ['GF']],
      ['Pepper Mushroom & Chicken RPR', '$4.50 each', []],
      ['Garlic Butter Prawns RPR', '$4.50 each', ['G']],
      ['Lemongrass Beef RPR', '$4.50 each', [], true],
      ['Tofu with Roasted Rice RPR', '$4.50 each', ['GF']],
      ['Avocado and Salad RPR', '$4.50 each', ['GF']],
      ['Lemongrass Tofu RPR', '$4.50 each', []],
    ],
  },
  {
    id: 'banh-mi',
    shortName: 'Bánh mì',
    eyebrow: 'Bánh mì',
    title: 'Vegan Rolls',
    description: 'A crispy baguette filled with savoury salad, iceberg lettuce, VieSauce, pickled carrots, cucumber, coriander, spring onions, and fried shallots.',
    dishes: [
      ['Pulled Pork & Cracklings Bánh Mì', '$12.50', ['P'], true],
      ['Lemongrass Beef Bánh Mì', '$12.50', []],
      ['Pepper Mushroom & Chicken Bánh Mì', '$12.50', []],
      ['Lemongrass Tofu Bánh Mì', '$12.50', []],
    ],
  },
  {
    id: 'pate-toast',
    shortName: 'Pâté & toast',
    eyebrow: 'Boards',
    title: 'Pâté & Toast',
    description: 'Vietnamese pâté on toasted baguette. Simple done properly or stacked with your choice of filling.',
    note: 'Contains peanuts, cashew nuts, onions, garlic, and wheat.',
    dishes: [
      ['The Original Trio (3)', '$10.90', ['P', 'G'], true],
      ['The Original Board (5)', '$13.90', ['P', 'G'], true],
      ['The Stacked Trio (3)', '$13.90', ['P', 'G']],
      ['The Stacked Board (5)', '$15.90', ['P', 'G']],
    ],
  },
  {
    id: 'pho',
    shortName: 'Phở',
    eyebrow: 'Soup',
    title: 'Vegan Phở Series',
    description: 'All phở is served with coriander and spring onions. Slow plant-based broths are layered, warming, and served with peanut hoisin dipping sauce on the side.',
    dishes: [
      ['Creamy Coconut Curry Phở', '$22.90', ['G', 'P'], true],
      ['Vegan Combination Phở', '$22.90', ['G'], true],
      ['Vegan Tofu & Mushroom Phở', '$18.90', ['G']],
      ['Vegan Chicken Phở', '$18.90', ['G']],
      ['Vegan Beef Phở', '$18.90', ['G']],
    ],
  },
  {
    id: 'fried-rice',
    shortName: 'Fried rice',
    eyebrow: 'Wok',
    title: 'Vegan Fried Rice',
    description: 'Basmati rice cooked over high heat the way fried rice deserves, bold and fragrant with ingredients that earn their place in the wok.',
    dishes: [
      ['Jack n Rice', '$17.90', [], true],
      ['Queen Tofu', '$18.90', []],
    ],
  },
  {
    id: 'sides',
    shortName: 'Sides',
    eyebrow: 'Extras',
    title: 'Sides',
    description: 'The right side dish makes a meal. Order one to start or add one to share.',
    dishes: [
      ['Forest Fries', '$12.90', [], true],
      ['Vegetable Spring Rolls (6) with Sweet Chilli Sauce', '$12.00', ['G']],
      ['Sweet Potato with Sea Salt', '$9.90', []],
      ['Salt & Pepper Crispy Tofu', '$9.90', []],
    ],
  },
]

export const menuLegend = [
  ['★', "Chef's signature"],
  ['P', 'Contains peanuts'],
  ['GF', 'Gluten free'],
  ['G', 'Contains garlic or onion'],
]
